README for Mac users.
====================================================================
Last modified: Mon Jun 12 05:35:09 UTC 2000

Ben Mesander(bam@dimensional.com) has contributed 
a macintosh executable for WeirdX. 
You will be able to start WeirdX on Mac very easily.


Content-Type: multipart/mixed; boundary="============_-1251765103==_============"
--============_-1251765103==_============
Content-Type: text/plain; charset="us-ascii"

Hi,

  I have created a macintosh executable for the 'misc' directory with
jbindery, an apple tool which creates an executable, given a classpath
and an initial class to run. You might want to provide this to
some of the people who have asked about this in order to test it.

  To use the provided executable, you need to install:

- Apple's MRJ 2.2 Java runtime. Where to get it:
  http://www.apple.com/java/

- A copy of the swingall.jar file from javasoft:
  http://java.sun.com/products/jfc/download.html
  Copy the swingall.jar file into the misc subdirectory.

- Unstuff the macweirdx archive with stuffit expander:
  http://www.aladdinsys.com/expander/index.html

- Click on the macweirdx program to run it.

  If users have success with this executable, let me know, and we can make a
fancy icon for it and add more polish.

  Hope this helps,
  --Ben

--============_-1251765103==_============
Content-Type: multipart/appledouble; boundary="============_-1251765103==_D============"

--============_-1251765103==_D============
Content-Transfer-Encoding: base64
Content-Type: application/applefile; name="%macweirdx.sit"
Content-Disposition: attachment; filename="%macweirdx.sit"

AAUWBwACAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAADAAAAPgAAAA0AAAAJAAAASwAAACAA
AAAIAAAAawAAABBtYWN3ZWlyZHguc2l0U0lUNVNJVCEBAACiAAEAAAAAAAAAAAAAAAAA
AAAAAAAA0EktANBJLUttDAAA0Ewx
--============_-1251765103==_D============
Content-Type: application/octet-stream; name="macweirdx.sit"
 ; x-mac-type="53495435"
 ; x-mac-creator="53495421"
Content-Disposition: attachment; filename="macweirdx.sit"
Content-Transfer-Encoding: base64

U3R1ZmZJdCAoYykxOTk3LTE5OTggQWxhZGRpbiBTeXN0ZW1zLCBJbmMuLCBodHRwOi8v
d3d3LmFsYWRkaW5zeXMuY29tL1N0dWZmSXQvDQoaAAUQAAAKJgAAAHIAAQAAAHKJdA2l
pVJlc2VydmVkpaUApaWlpQEAADkAALVjPQm1Yz0JAAAAAAAAAAAAAAAAAAmfUwAAAAAA
AAAAAAAAAAAAbWFjd2VpcmR4AAGTjUFQUEw/Pz8/AQAAbAEhAAAAAAAAAAAAAIAAAAAA
AAAAAAASTgAACUkMlwAADQAMwPie2ZpsZbYyOeWe3JMrAKdJ6F7Zyjy/JlFOWzdh66Ae
T4/Tw3dszTj9NiP0lK15UjvPjq8DZuc2W1kXI5tt1se6zthm+9lm0Tpy7JTtN5b7PLKP
bjKgZLAZ4Udun4RN6hhht8lmRzjhF4vwTsppt+mWsL1yN/6Aqyu7BpHbZB/ZRza5TW6T
6SbHyGCT32TIycYHoJcDgFsBGACYj6cBT4ZLBRMinwrHRD5CvHw4MsTvIK1hcTA5F+l/
+5Ird1XfhJneqwCaMTxBVbzKUn+vZYXVam0g1tWNq1c3rlpNKDy97MV7skcJBUygYoqY
3IwMaQud7mwLDwaJL8FvCyeJsSbER8ORHcv+4cX0t6joi0vpXNzGC2IwGU5H/27gu1A0
r83b0t4fjERaw1sTfGJHs68f5bbw23jiiMcj4YASCZIIPpgOJ4JJkuoPElesL0g2JHgh
GhRTpI0XeSGYIKkY2RokYTGZ4iORYJ9Z5xBJMJGIJYhx+TISCwTSiUSwjwz1hyNBEonx
fWFRIDxJ9vOUFsnLJ8ZNy8xkbhsfIO524k2LqXA0SEIoQrEkipns57cFUWlQRK2BGGoK
pCI7ZnQTdCtFPQzEovE0htpcfLpDHBRjQ+IZtLwRVIr1YeZO+ByzSaPZlA6nFIYOyjCK
q0byfIrfD1uYTbu1Pdae+p4VPSuRY8PzUzJ+GdodYFSG9Ttn7++8UQFPFwCV48sOOmvs
4qN7dhVI5Xh6cMk1nLV4Yv7X2YDJTgLM3k+3f/vV7r0Wm8vdtN4pZEfIQgHgKrETj7m8
1pB9Lg6k7akTfpVh/IWfR3OOd8Do+sN2UPBXojm6ucnhcyibO4kWd79kmUs8bD9ouDE4
5tnryskHljdLC6rauDFVeVVUWoAz6sJpn7NOWmy1jT5zZINFa7Ud2v/chhcuCrrFDwEj
LY4zh/ZbbdnJIxuWs1IpIlcUpASRKQXRUbYjp+o/vJGyHTl1tYJMOXJgPryR+zHmYLcy
nWeHoaqlTpYFlVNwCpQza9+Wvc4jCnsPN6Z+PDtFo8JerrB2u2tiUIEOA7yx5FuVnwEG
TxWe6uoYkNd+uWAx+6hVrbJDRihRueDzZRfaXS2uyDX/bxSWXShR5nVeOzv+2rj/pIIS
QYe7Kr2uRYv9eb5BMCBj3rBc9tPC/sNWtd4Omq19J+3WtVDEvY+t4cdGqIBacHbtKbsu
y8p5oeyCH+ThAgNRBR9ANIvnpG8PZXhxQpZvmkXxmzwbNsC87CveJn0TqKMgl5P7u9yt
F/UNXNoyq9tdFQP9km9UdqP33eh9N6hNC1Pgby29y8AozutPMwaGzbDjZzN+45KddJPC
tAt668I32dfRe2SWTG+vXvjmntcfITEwEAuUnTpmhPZdLbvEY6S5y22qRM266mbLXIvO
ouXG5IylTlpQwFI455EB97tQXd07vavp6wWel267gTZZdDewhumNP8mBMaTi0uxl+IJp
GCpIVCptQYdDGkRKLCzoWi/eAz43l6Yd4MjJOfIEl3b9kfbs+HUwLN2tneTStDNR1Q99
bvbypUsd34dy7INyUidVCDpiX2fCxD7p2+u5puuZblPKoX0aWoBbjCFNHBM3s8l/vqVh
znFBQ+wjfaRzZBnpJR6iHekgduxCumNMfriKPfUWoJfSJdJb1XbmLdBYjaCq0vr1Kx/i
0J8zWVB5vrTpZflqCzapoKGdiVqxbWZ0tl6cPbulgakTVFlZcRFQz4TPjTmKgVY/QHWE
hvUD2DZF0cRTLxe0q/7soqZrr99L7wU3XNmGje/52Bd6r/jqDV/QWRPpHWn+wJ/qW/5U
95qf4dL4GwNTdopLm7YXa2iLYzZ1Sp9P0rzmO57mFZsdO8Bfttwr1a6zybLFBFoygLeN
J7e4q6NSLdGF3qCpx98D8nWLehsQWwAvZa4J+fqh71XtbrGH9Prn8drDyNeDqm2MQV1T
yfUo28AyB1MhQlmNCOXsDlmWcqPiqJQtdR7JfnbUk7Vm783+jMwR1jjeBgb1MHEwlD5r
ppM345iQwTWpBcdvgfLuUHh3JKC09HTmbocMfo3TjArNoMVTj6eBFWXIPtbhxkxmUOEu
a2V1b01v3ovccfbyEqJ4F0oIronccerdGhCMbFSSLDZMa4YbY552Hsn/KAtTa4vL2Hpl
fmDs3W7zj4q12CqYEWw1dGakzpFjrKjlUtW5D3+Y5bPlwIq5l1AZoyhrbNEIWpMtPhQP
+ItMtuiahsEOt7JhFrsdZiFyDs9fUd20GY9utlaiOwD7WfF9QBVqqgKmrC6LlhWvY+fA
L1jxT5SpUZjnsRGkEGZAopwihXPCb9LXAZGkvjLHO5LkmpAAM4R7vJlnzf6SD3Z9k6YH
0VkK+jhFKZ9qpHqpC+hqbSEP1jr0KjdFPb0bb5e5K/4inA25K+sxDdxXakHx9hw6qaFO
kqLWi5rtNIlHpdm3Hi/q6eX6FgHvNBq802jx/jtBej1u7iT3AEC322Jr93mXrjODLjtS
JYLeOZ9UClW0Pa3lK7ADhAXH7VtL49DuEIoM5afG/e8ZDF77iJnrQRV7uZMorQSv+kY4
zuyGTEeHVYeMu/B5wTwQSPChlHkoGE70bTd30rFLufsrfpQC09nMNX305qIDRkxHInlQ
zeLbzwE+Ek5SlDlAN+vx8SMspmLJfsJ+vPw7R3Z2OSnJMG9KV5A9wCf+/Sj0l88wL/di
13ebnM2co78pGseymX4Qu/VpouFkAJl6qhlPvFKgsyq475ZNjU3B5GAqFicbYpG+YKIx
b01dvdlqrq9vpAoKlLxbxTAKo3woHs2HAJ9F7oNuSMPX4CBj+pdrxVsjfGCwnx8a/Cv/
n/FRbw2Kt0NCC5s5eCOhB/+TUH1yCN+48FXqfxmd3/7pH6RCv97c7CFtnZs9txO69nZC
P3TrEzcyil++dZVJXfLfuH3C6ZdvR13XuPJ3B/r4/NH/H0oeyzb0DiNUwXAwl16ZEUs0
NftacX6YPizjvIc+Q+HifY5Wrw/x53EPncc8Dm8bzifam91dyD/t8vhYxN/2eN344A3v
4bwBVara29e7cC7Z6HXjmzmzqL1583qcayBTaHH65bHf50HlBkYv+9PYgwrEKNgTM/uK
C/+NULC1NzHlSl7AemZ2F+ef/fO8R2Yw/as3sbM3sfMz2Lzf5REFw/98APwfAAAA
--============_-1251765103==_D============--
--============_-1251765103==_============--
